/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.Person;
import repository.PersonDirectory;

/**
 *
 * @author kpsingh
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private PersonDirectory personDir;
    private Person person;
    
    public ViewJPanel() {
        initComponents();
    }
    
    public ViewJPanel(PersonDirectory personDir) {
        initComponents();
        personTable.removeAll();
        this.personDir = personDir;
        populateTable(personDir);
    }
    
    private void populateTable(PersonDirectory personDir) {
        //Write funcationality to add dir data into table
        DefaultTableModel model = (DefaultTableModel) personTable.getModel();
        model.setRowCount(0);
        
        //for each loop
        for ( Person person : personDir.getPersonDirectory()){
                   
            Object[] row = new Object[7];
            row[0] = person.getName();
            row[1] = person.getAge();
            
            model.addRow(row);
        }
    }
    
//    private void populateTableV1(Person person) {
//        //Write funcationality to add dir data into table
//        DefaultTableModel model = (DefaultTableModel) personTable.getModel();
//        model.setRowCount(0);
//        
//        //for each loop
//        
//                   
//            Object[] row = new Object[7];
//            row[0] = person.getName();
//            row[1] = person.getAge();
//            
//            model.addRow(row);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        lblTitle.setText("View Person Details");

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "Temperature", "Blood Pressure", "Respiration Rate", "Community Namel"
            }
        ));
        jScrollPane1.setViewportView(personTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(lblTitle)
                .addContainerGap(434, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable personTable;
    // End of variables declaration//GEN-END:variables
}
